create schema if not exists hive.tpcds_parquet_300;
use hive.tpcds_parquet_300;
CREATE TABLE hive.tpcds_parquet_300.call_center WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.call_center;
CREATE TABLE hive.tpcds_parquet_300.catalog_page WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.catalog_page;
CREATE TABLE hive.tpcds_parquet_300.catalog_returns WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.catalog_returns;
CREATE TABLE hive.tpcds_parquet_300.catalog_sales WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.catalog_sales;
CREATE TABLE hive.tpcds_parquet_300.customer WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.customer;
CREATE TABLE hive.tpcds_parquet_300.customer_address WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.customer_address;
CREATE TABLE hive.tpcds_parquet_300.customer_demographics WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.customer_demographics;
CREATE TABLE hive.tpcds_parquet_300.date_dim WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.date_dim;
CREATE TABLE hive.tpcds_parquet_300.household_demographics WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.household_demographics;
CREATE TABLE hive.tpcds_parquet_300.income_band WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.income_band;
CREATE TABLE hive.tpcds_parquet_300.inventory WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.inventory;
CREATE TABLE hive.tpcds_parquet_300.item WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.item;
CREATE TABLE hive.tpcds_parquet_300.promotion WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.promotion;
CREATE TABLE hive.tpcds_parquet_300.reason WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.reason;
CREATE TABLE hive.tpcds_parquet_300.ship_mode WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.ship_mode;
CREATE TABLE hive.tpcds_parquet_300.store WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.store;
CREATE TABLE hive.tpcds_parquet_300.store_returns WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.store_returns;
CREATE TABLE hive.tpcds_parquet_300.store_sales WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.store_sales;
CREATE TABLE hive.tpcds_parquet_300.time_dim WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.time_dim;
CREATE TABLE hive.tpcds_parquet_300.warehouse WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.warehouse;
CREATE TABLE hive.tpcds_parquet_300.web_page WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.web_page;
CREATE TABLE hive.tpcds_parquet_300.web_returns WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.web_returns;
CREATE TABLE hive.tpcds_parquet_300.web_sales WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.web_sales;
CREATE TABLE hive.tpcds_parquet_300.web_site WITH (format = 'parquet') AS SELECT * FROM tpcds.sf300.web_site;